### ISSUE TITLE
Global Hash creates multiple global tags in the config

### ISSUE THREAD

**Issue by tuxfight3r** [crayfishx/puppet-rsyslog#11]
Rather than passing all the values in the global hash inside the global tag it creates a global tag per entry in the syslog config file.
```
rsyslog::server::global_config:
  umask:
    value: '0000'
    type: legacy
    priority: 01
  RepeatedMsgReduction:
    value: 'on'
    type: legacy
  PrivDropToUser:
    value: 'syslog'
    type: legacy
  PrivDropToGroup:
    value: 'syslog'
    type: legacy
  parser.escapeControlCharactersOnReceive:
    value: 'on'
  workDirectory:
    value: '/var/spool/rsyslog'
  maxMessageSize:
    value: '64k'
```
the above code produces content like below
```
$PrivDropToGroup syslog
$PrivDropToUser syslog
$RepeatedMsgReduction on
global (
  maxMessageSize="64k"
)
global (
  parser.escapeControlCharactersOnReceive="on"
)
global (
  workDirectory="/var/spool/rsyslog"
)
$umask 0000
```
but it should be like this
```
$PrivDropToGroup syslog
$PrivDropToUser syslog
$RepeatedMsgReduction on
global (
  maxMessageSize="64k"
  parser.escapeControlCharactersOnReceive="on"
  workDirectory="/var/spool/rsyslog"
)
$umask 0000
```
